Sprint2
ClevertecFrontendLab/sprint2-liahrothstein pull request #1
Opened 2023-02-09 15:41 UTC by liahrothstein

2023-02-09 15:44 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 320px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/Test%20width%20320px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/Test%20width%20768px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/slider%20after%201440px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/slider%20before%201440px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/slider%20more%20two%20foto%201440px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/slider%20not%20foto%201440px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675957453/slider%20one%20foto%201440px.png)

2023-02-09 17:24 UTC, SergeyGlazun requested changes

2023-02-09 17:24 UTC, SergeyGlazun commented on .editorconfig
> +root = true
![image](https://user-images.githubusercontent.com/70904466/217889748-b7307946-8d67-474b-a937-304950563540.png)

2023-02-09 17:24 UTC, SergeyGlazun commented on .editorconfig
> +[*]
![image](https://user-images.githubusercontent.com/70904466/217889860-51f91094-97a1-4a4d-b521-1580d8813b1c.png)
не закрывает

2023-02-09 17:24 UTC, SergeyGlazun commented on .editorconfig
> +insert_final_newline = true
![image](https://user-images.githubusercontent.com/70904466/217890038-0503834b-e94f-4245-a495-4059d39647fd.png)
пропал бургер

2023-02-09 17:24 UTC, SergeyGlazun commented on .editorconfig
> +max_line_length = 100
![image](https://user-images.githubusercontent.com/70904466/217890147-7bedc689-aa71-41ce-98a7-9144fad22a27.png)
не выделена активная книга

2023-02-09 17:24 UTC, SergeyGlazun commented on .editorconfig
> +indent_size = 4
![image](https://user-images.githubusercontent.com/70904466/217890229-b85f2deb-873f-40ce-82cb-83f9b4833b66.png)

2023-02-09 17:24 UTC, SergeyGlazun commented on .editorconfig
> +indent_style = space
![image](https://user-images.githubusercontent.com/70904466/217890330-12110825-d7f5-44b0-8918-81f1544d0e7b.png)
сделать темнее на белом фоне выгледит странно

2023-02-09 18:37 UTC, liahrothstein commented on .editorconfig
> +[*]
что именно не закрывает? бургер при нажатии?

2023-02-09 19:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 320px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/Test%20width%20320px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/Test%20width%20768px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/slider%20after%201440px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/slider%20before%201440px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/slider%20more%20two%20foto%201440px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/slider%20not%20foto%201440px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675970659/slider%20one%20foto%201440px.png)

2023-02-09 20:13 UTC, SergeyGlazun requested changes

2023-02-09 21:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 320px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/Test%20width%20320px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/Test%20width%20768px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/slider%20after%201440px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/slider%20before%201440px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/slider%20more%20two%20foto%201440px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/slider%20not%20foto%201440px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/liahrothstein/1675978460/slider%20one%20foto%201440px.png)

2023-02-10 05:56 UTC, SergeyGlazun approved these changes

2023-02-10 11:28 UTC, merged